create database customer_behaviour;

use customer_behaviour;

alter user 'root'@'localhost' IDENTIFIED BY 'root123'; FLUSH privileges;

alter user 'root'@'localhost' IDENTIFIED WITH mysql_native_password by 'root123';

flush privileges;

select * from customer_data;

-------------------------------------------------------------------------------------------------------------------
-- Business Questions
-------------------------------------------------------------------------------------------------------------------
-- Q1. Which category generates highest revenue?

select category , round(sum(purchase_amount),2) as revenue
from customer_data
group by category
order by revenue desc;

-- Electronics Category has highest Revenue

-- Impact:
-- 			1. Will help prioritize high performing categories.
-- 			2. Optimize Inventory Planning
-- 			3. Improves Marketing ROI

-------------------------------------------------------------------------------------------------------------------
-- Q2. Are discounts actually increasing purchase value?

select discount_applied , round(sum(purchase_amount),2) as total_revenue , 
round(avg(purchase_amount),2) as average_revenue
from customer_data
group by discount_applied;

-- Average Revenue seems to be increasing but total is still low

select * from customer_data;

select frequency_of_purchases, 
sum(case when discount_applied = "Yes" then 1 else 0 end) as discount_yes,
sum(case when discount_applied = "No" then 1 else 0 end) as discount_no,
count(*) as total
from customer_data
group by frequency_of_purchases
order by frequency_of_purchases;

-- Bi-Weekly purchases which are the most frequent among the group seems have lower purchase when discount is
-- offered. In fact people are tending to buy more products which do not have discount.

-- Business Impact:
-- Evaluated discount effectiveness through SQL-based analysis; 
-- identified that discounted transactions had higher average revenue (₹219 vs ₹182), 
-- but overall revenue remained lower due to limited adoption, highlighting the need for targeted discount 
-- strategies.

-------------------------------------------------------------------------------------------------------------------
-- Q3. What is the total revenue generated by male and female customer ?

select * from customer_data;

select gender, round(sum(purchase_amount) , 2) as revenue
from customer_data
group by gender
order by revenue desc;

select round(sum(purchase_amount) , 2) as revenue
from customer_data 
where gender in ("Male" , "Female");

-- Males spending more than females

-- Impact:
-- 			1. Help design targetted marketing campaign
-- 			2. Improves Customer segmentation startegy
-- 			3. Enhances personalization efforts

-------------------------------------------------------------------------------------------------------------------
-- Q4. Which customer used a discount but still spent more then the average purchase amount ?

select * from customer_data;

select customer_id, round(sum(purchase_amount),2) as spent
from customer_data
where discount_applied = "Yes"
group by customer_id
having spent>(select round(avg(purchase_amount),2) from customer_data)
order by spent desc;

-- Customer 4977 is using the discount coupons but is spending higher than average spent

-- Impact:
-- 			1. Identifies premium discount sensitive customers
-- 			2. Targetted discount campaigns can be done
-- 			3. Improves customer retention

-------------------------------------------------------------------------------------------------------------------
-- Q5. Which are the top/bottom 5 products with the highest average review rating.

select * from customer_data;

-- Top 5
select item_purchased, round(avg(review_rating),2) as avg_review_rating
from customer_data
group by item_purchased
order by avg_review_rating desc limit 5;

-- Bottom 5
select item_purchased, round(avg(review_rating),2) as avg_review_rating
from customer_data
group by item_purchased
order by avg_review_rating limit 5;

-- Best products are gloves and sandals as per reviews
-- Worst products are phone and headphones

-- Impact:
-- 			1. Promotes high performing products
-- 			2. Gives direction to improvements on lower rated products
-- 			3. Enhances Customer experience

-------------------------------------------------------------------------------------------------------------------
-- Q6. Average purchase: Standard vs Express shipping

select * from customer_data;

select shipping_type, count(distinct(customer_id)) as number_of_orders, round(avg(purchase_amount),2) as average_purchase
from customer_data
group by shipping_type
order by average_purchase desc;

select shipping_type, count(distinct(customer_id)) as number_of_orders, round(avg(purchase_amount),2) as average_purchase
from customer_data
group by shipping_type
having shipping_type in ("Express" , "Standard")
order by average_purchase desc;

-- Average Purchase is more in Express type shipping method than Standard even though
-- number of orders are more in standard shipping. This might mean high value purchases correlating with Express 
-- Shipping and also both largely differ from the rest in terms of average purchase amount

-- Impact:
-- 			1. Helps optimize shipping pricing strategy
-- 			2. Increase adoption to shipping strategy
-- 			3. Increase average order value

-------------------------------------------------------------------------------------------------------------------
-- Q7. Do subscribed customers spend more ? Compare average speed and total revenue between
-- subscribers and non-subscribers.

select * from customer_data;

select subscription_status, count(distinct(customer_id)) as numbers, round(avg(purchase_amount),2) as avg_revenue, round(sum(purchase_amount),2) as total_revenue
from customer_data
group by subscription_status
order by total_revenue desc;

-- The people who subscribed are less in numbers but they have the highest avg revenue generation
-- But still highest revenue is generated by people who havent subscribed

-- Impact:
-- 			1. Validates subscription model performance
-- 			2. Improves customer loyalty programs
-- 			3. Increases customer lifetime value (CLV)

-------------------------------------------------------------------------------------------------------------------
-- Q8. Top 5 products with highest discount usage %

select * from customer_data;

select item_purchased, sum(case when discount_applied = "Yes" then 1 else 0 end)*100.0/count(*) as perc_of_users
from customer_data
group by item_purchased
order by perc_of_users desc limit 5;

-- Laptop, Phone, Headphones, Hats and Watches are products with highest discount percentage

-- Impact:
-- 			1. Identifies Discount driven products
-- 			2. Helps optimize pricing strategy
-- 			3. Reduce Profit Margin loss

-------------------------------------------------------------------------------------------------------------------
-- Q9. Segment customer into new, returning and loyal based on their total number of previous purchase,
-- and show the count of each segment.

select * from customer_data;

select min(previous_purchases) , max(previous_purchases) , avg(previous_purchases)
from customer_data;

select
	case
		when previous_purchases = "0" then "New Customer"
        when previous_purchases between 1 and 20 then "Returning Customer"
		else "Loyal Customer"
	end as customer_segment,
count(*) as customer_count
from customer_data
group by customer_segment
order by customer_count desc;

-- We showed the count of each cutomer segment

-- Impact:
-- 			1. Personalized Marketing and targetted ads
-- 			2. Improves retention strategies
-- 			3. Increase conversion rates

-------------------------------------------------------------------------------------------------------------------
-- Q10. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?

select * from customer_data;

select min(previous_purchases), max(previous_purchases), avg(previous_purchases)
from customer_data;

SELECT 
    CASE
        WHEN previous_purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Non Repeat Buyers'
    END AS repeatability,
    COUNT(*) AS total_customers,
    SUM(CASE
        WHEN subscription_status = 'Yes' THEN 1
        ELSE 0
    END) AS subscribers,
    round((SUM(CASE
        WHEN subscription_status = 'Yes' THEN 1
        ELSE 0
    END) * 100) / COUNT(*),2) AS subscription_rate
FROM
    customer_data
GROUP BY repeatability;

-- Repeat Buyers are more but their subscription rate is low probably due to some issues with quality

-- Impact:
-- 			1. Proper segmentation of churn data
-- 			2. Increases retention rate
-- 			3. Targetted attention can be given

-------------------------------------------------------------------------------------------------------------------
-- Q11. What are the top 3 most purchased products within each category ?

select * from customer_data;

select item_purchased, count(customer_id) as count_of_purchases, round(avg(purchase_amount),2) as avg_revenue, round(sum(purchase_amount),2) as total_revenue
from customer_data
group by item_purchased
order by count_of_purchases desc limit 3;

with cte as
(
	select category, item_purchased, count(item_purchased) as purchase_count,
    rank() over(partition by category order by count(item_purchased) desc) as rank_given
from customer_data
group by category, item_purchased
)
select * from cte
where rank_given <=3;

-- Shirt, shoes and Jewlry are the top 3 products being sold and are the most revenue generating products but
-- within each category we see the finer details

-- Impact:
-- 			1. Improves product placement and recommendations
-- 			2. Inventory optimization can be done
-- 			3. Increase sales through best sellers

-------------------------------------------------------------------------------------------------------------------
-- Q12. What is the revenue contribution of each age group ?

select * from customer_data;

select min(age), max(age)
from customer_data;

select
	case
		when age between 18 and 30 then "Young Adult"
        when age between 31 and 50 then "Older Adult"
	else "Senior Citizen"
    end as age_group, round(sum(purchase_amount),2) as revenue
from customer_data
group by age_group
order by revenue desc;

-- Highest Revenue contribution from Senior citizens followed by older adults as expected

-- Impact:
-- 			1. Enable age based targetting strategy
-- 			2. Enhances marketting efficieny
    

-------------------------------------------------------------------------------------------------------------------
