create database customer_behaviour;

use customer_behaviour;

alter user 'root'@'localhost' IDENTIFIED BY 'root123'; FLUSH privileges;

alter user 'root'@'localhost' IDENTIFIED WITH mysql_native_password by 'root123';

flush privileges;

select * from customer_data;

-------------------------------------------------------------------------------------------------------------------
-- Business Questions
-------------------------------------------------------------------------------------------------------------------
-- Q1. Which category generates highest revenue?

select category , round(sum(purchase_amount),2) as revenue
from customer_data
group by category
order by revenue desc;
-- Electronics Category has highest Revenue
-- Impact:
-- 			1. Will help prioritize high performing categories.
-- 			2. Optimize Inventory Planning
-- 			3. Improves Marketing ROI

-------------------------------------------------------------------------------------------------------------------
-- Q2. Are discounts actually increasing purchase value?

select discount_applied , round(sum(purchase_amount),2) as total_revenue , 
round(avg(purchase_amount),2) as average_revenue
from customer_data
group by discount_applied;

-- Average Revenue seems to be increasing but total is still low

select * from customer_data;

select frequency_of_purchases, 
sum(case when discount_applied = "Yes" then 1 else 0 end) as discount_yes,
sum(case when discount_applied = "No" then 1 else 0 end) as discount_no,
count(*) as total
from customer_data
group by frequency_of_purchases
order by frequency_of_purchases;

-- Bi-Weekly purchases which are the most frequent among the group seems have lower purchase when discount is
-- offered. In fact people are tending to buy more products which do not have discount.

-- Business Impact:
-- Evaluated discount effectiveness through SQL-based analysis; 
-- identified that discounted transactions had higher average revenue (₹219 vs ₹182), 
-- but overall revenue remained lower due to limited adoption, highlighting the need for targeted discount 
-- strategies.

-------------------------------------------------------------------------------------------------------------------
-- What is the total revenue generated by male and female customer ?

select * from customer_data;

select gender, round(sum(purchase_amount) , 2) as revenue
from customer_data
group by gender
order by revenue desc;

select round(sum(purchase_amount) , 2) as revenue
from customer_data 
where gender in ("Male" , "Female");
-------------------------------------------------------------------------------------------------------------------
-- Which customer used a discount but still spent more then the average purchase amount ?
-------------------------------------------------------------------------------------------------------------------
-- Which are the top/bottom 5 products with the highest average review rating.
-------------------------------------------------------------------------------------------------------------------
-- Average purchase: Standard vs Express shipping
-------------------------------------------------------------------------------------------------------------------
-- Do subscribed customers spend more ? Compare average speed and total revenue between
-- subscribers and non-subscribers.
-------------------------------------------------------------------------------------------------------------------
-- Top 5 products with highest discount usage %
-------------------------------------------------------------------------------------------------------------------
-- Segment customer into new, returning and loyal based on their total number of previous purchase,
-- and show the count of each segment.
-------------------------------------------------------------------------------------------------------------------
-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?
-------------------------------------------------------------------------------------------------------------------
-- What are the top 3 most purchased products within each category ?
-------------------------------------------------------------------------------------------------------------------
-- What is the revenue contribution of each age group ?
-------------------------------------------------------------------------------------------------------------------
